name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.14'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev openjdk-17-jdk
          pip install --upgrade pip setuptools
          pip install buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          # 1. Инициализируем buildozer (создаем папки)
          buildozer android help || true
          
          # 2. Прямое принятие лицензий через sdkmanager
          # Мы заходим в папку, куда buildozer скачал SDK, и подписываем всё
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          export SDK_PATH=$(buildozer android dump | grep "ANDROIDSDK=" | cut -d'=' -f2 | xargs)
          if [ -d "$SDK_PATH" ]; then
            yes | $SDK_PATH/tools/bin/sdkmanager --licenses || true
          fi
          
          # 3. Запуск основной сборки. Добавляем --profile для надежности
          buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Zartas-Installer
          path: bin/*.apk
